name: 'polyfill-glibc-action'
description: 'polyfill-glibc binary patcher for backwards glibc compatibility'
branding:
  icon: 'box'
  color: 'green'
inputs:
  install:
    description: "install polyfill-glibc"
    default: 'true'
    required: false
  target:
    description: "path to ELF binary"
    default: ''
    required: false
  glibc:
    description: "glibc target version"
    default: '2.17'
    required: false
outputs:
  binary:
    description: "Polyfilled binary"
runs:
  using: 'docker'
  image: 'docker://ghcr.io/lmangani/polyfill-glibc-action:latest'
